name: branch-releases

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2
      # install deps
      - run: npm ci
      # pack packs
      - run: npm run pack

      # Create a zip file with all files required by the module to add to the release
      - run: zip -r ./module.zip module.json LICENSE packs/ assets/

      # Download module.zip artifact for local testing
      -name: Download a single artifact
       uses: actions/download-artifact@v4
       with:
        name: module.zip
